do
    require("./datastructures/circularbuffer/tests")()
    require("./datastructures/circularqueue/tests")()
    require("./datastructures/queue/tests")()
    require("./datastructures/set/tests")()
end

do
    require("./moving-average/array/tests")()
    require("./moving-average/circularbuffer/tests")()
    require("./moving-average/circularqueue/tests")()
end

do
    require("./unit-conversion/tests")()
end
