do
    local _ = require("./datastructures/circularbuffer/tests")
    local _ = require("./datastructures/circularqueue/tests")
    local _ = require("./datastructures/queue/tests")
    local _ = require("./datastructures/set/tests")
end

do
    local _ = require("./moving-average/array/tests")
    local _ = require("./moving-average/circularbuffer/tests")
    local _ = require("./moving-average/circularqueue/tests")
end

do
    local _ = require("./unit-conversion/tests")
end
